import Head from "next/head";
import { Data } from "@/src/components/types";
import { HomePage } from "@/src/components/HomePage";
import styles from  '../styles/Home.module.css'
export default function Home({ data }: { data: Data }) {
  return (
    <>
      <Head>
        <title>SR Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.imgur.com/wG9d64p.png" />
      </Head>
      <main>
        <div className={styles.container}>
          <p>
            Welcome to our website, your go-to destination for information about
            events and functions taking place in cities all around the world. We
            understand how difficult it can be to keep track of all the events
            and functions happening in your city, let alone in other cities you
            may be interested in visiting. That's why we created this website –
            to make it easy for you to stay informed and plan your activities
            ahead of time.
          </p>
        </div>
        <HomePage {...data} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://raw.githubusercontent.com/timeToCode-ali/nextjs-tutorial/main/data/data.json"
  );
  const data = (await res.json()) || null;

  return {
    props: { data }, // will be passed to the page component as props
  };
}
